project:
  type: website
  output-dir: docs

website:
  title: "yimerwas.github.io"
  description: "A personal website"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - icon: github
        href: https://github.com/yimerwas
      - icon: linkedin
        href: https://www.linkedin.com/in/yimerwas/

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    toc-title: "Table of Contents"
    toc-depth: 2
    code-fold: true
    number-sections: true

